### ISSUE TITLE
在点击“获取授权”后，报下面这个错误

### ISSUE THREAD

**Issue by ghost** [gucheen/letBDdoit#1]
错误代码：redirect_uri_mismatch
错误信息：Invalid redirect uri
详细描述：授权回调页地址错误，具体内容请开发者参考“redirect uri”验证方式

看来还得和你后台填写的回调地址一致

**Comment by gucheen** [comment]
@kskgy 感谢你对这个应用的兴趣，由于我把这个应用的 api 拿来做了其他服务，所以这里的 key 已经失效，回调地址也没有维护，目前回调地址和应用后台设置并不一致
